import type { GenerationV2AuthorityTransactionContextV2 } from '../../infra/db/repo/generationV2AuthorityTransactionInternal'
import { isGenerationExecutionOperationBundleForContextV2,type GenerationExecutionOperationBundleV2 } from '../../infra/db/repo/generationExecutionV2Repo'
import type { LocalEndpointProfileV2 } from '../../infra/db/repo/localEndpointProfileV2Repo'
import { isOllamaChatRequestHistoryFactForContextV2,type OllamaChatRequestHistoryFactV2 } from '../../infra/db/repo/ollamaChatNativeHistoryV2Repo'
import { createSemanticConsumptionLedgerV2 } from '../../src/next/generation-v2/compiler/semanticConsumptionLedgerV2'
import { createNoCredentialHeaderPlanV2,issuePreparedProviderRequestV2,type PreparedProviderRequestV2 } from '../../src/next/generation-v2/compiler/preparedProviderRequestV2'
import { compileOllamaNativeChatRequestV1 } from '../../src/next/generation-v2/providers/ollama-chat/chatRequestV1'
import { buildOllamaNativeChatRequestHistoryV1 } from '../../src/next/generation-v2/providers/ollama-chat/nativeMessagesV1'
import { readOllamaChatEndpointV2,readOllamaThinkingControlV2 } from '../../src/next/generation-v2/providers/ollama-chat/verifiedContractV2'
export function compileOllamaChatPreparedRequestV2(input:Readonly<{context:GenerationV2AuthorityTransactionContextV2;execution:GenerationExecutionOperationBundleV2;profile:LocalEndpointProfileV2;history:OllamaChatRequestHistoryFactV2}>):PreparedProviderRequestV2{
  if(!isGenerationExecutionOperationBundleForContextV2(input.execution,input.context)||!isOllamaChatRequestHistoryFactForContextV2(input.history,input.context)||!['committed','streaming','completed','failed','cancelled'].includes(input.execution.operation.state))throw new Error('GENERATION_V2_OLLAMA_COMPILER_AUTHORITY_INVALID')
  const {operation,snapshot,capability}=input.execution,b=snapshot.providerBinding,i=snapshot.semanticIntent,g=i.generation
  if(b.providerId.value!=='ollama'||b.protocolContractId.value!=='ollama-chat-v1'||b.endpointProfileId.value!==input.profile.endpointProfileId||b.credentialScopeId.value!==input.profile.credentialScopeId||b.operation!=='text'||b.endpointBinding.kind!=='provider_managed_set'||b.endpointBinding.endpointSetRevision.value!==input.profile.profileRevision)throw new Error('GENERATION_V2_OLLAMA_COMPILER_BINDING_INVALID')
  if(g.candidateCount!==undefined||g.frequencyPenalty!==undefined||g.presencePenalty!==undefined||i.web.mode!=='disabled'||i.image.mode!=='disabled'||i.tools.mode!=='disabled'||i.attachments.length||i.providerExtension.kind!=='none')throw new Error('GENERATION_V2_OLLAMA_COMPILER_EXPLICIT_FIELD_UNSUPPORTED')
  const messages=buildOllamaNativeChatRequestHistoryV1(input.history);const compiled=compileOllamaNativeChatRequestV1({model:b.modelId.value,messages,thinkingControl:readOllamaThinkingControlV2(input.profile),reasoning:{mode:i.reasoning.mode,...(i.reasoning.mode==='enabled'&&i.reasoning.effort?{effort:i.reasoning.effort}:{})},generation:{maxOutputTokens:g.maxOutputTokens,temperature:g.temperature,topP:g.topP,topK:g.topK,seed:g.seed,stop:g.stop,repetitionPenalty:g.repetitionPenalty}})
  const entries=[{kind:'consumed' as const,path:'reasoning.mode',disposition:'encoded' as const,nativeField:'think',evidence:'ollama-chat-v1'},
    {kind:'consumed' as const,path:'web.mode',disposition:'accepted_no_wire' as const,nativeField:null,evidence:'ollama-chat-v1'},
    {kind:'consumed' as const,path:'image.mode',disposition:'accepted_no_wire' as const,nativeField:null,evidence:'ollama-chat-v1'},
    {kind:'consumed' as const,path:'tools.mode',disposition:'accepted_no_wire' as const,nativeField:null,evidence:'ollama-chat-v1'},
    {kind:'consumed' as const,path:'providerExtension.kind',disposition:'accepted_no_wire' as const,nativeField:null,evidence:'ollama-chat-v1'},
    ...(i.reasoning.mode==='enabled'&&i.reasoning.effort?[{kind:'consumed' as const,path:'reasoning.effort',disposition:'encoded' as const,nativeField:'think',evidence:'ollama-chat-v1'}]:[]),
    ...([['maxOutputTokens','num_predict'],['temperature','temperature'],['topP','top_p'],['topK','top_k'],['seed','seed'],['stop','stop'],['repetitionPenalty','repeat_penalty']] as const).flatMap(([key,native])=>g[key]===undefined?[]:[{kind:'consumed' as const,path:`generation.${key}`,disposition:'encoded' as const,nativeField:`options.${native}`,evidence:'ollama-chat-v1'}])]
  return issuePreparedProviderRequestV2({operationId:operation.operationId.value,answerRootId:operation.resultAnswerRootId.value,requestSequence:1,providerId:'ollama',endpointProfileId:input.profile.endpointProfileId,credentialScopeId:input.profile.credentialScopeId,contractId:'ollama-chat-v1',modelId:b.modelId.value,effectiveEndpointId:input.profile.endpointProfileId,endpoint:readOllamaChatEndpointV2(input.profile),headersPlan:createNoCredentialHeaderPlanV2(),body:compiled.preparedBody,ledger:createSemanticConsumptionLedgerV2(entries),capabilityRevision:capability.revision.value,snapshotHash:snapshot.snapshotHash.value})
}
