import {randomUUID} from 'node:crypto';import type BetterSqlite3 from 'better-sqlite3'
import {AttachmentAssetV2Repo} from '../../infra/db/repo/attachmentAssetV2Repo';import {ConversationGraphV2Repo,type PendingAnswerActionV2,type PendingEditedTurnV2,type PendingInitialTurnV2} from '../../infra/db/repo/conversationGraphV2Repo'
import {GenerationConfigV2Repo} from '../../infra/db/repo/generationConfigV2Repo';import {withSynchronousGenerationCommandFactsAuthorityV2} from '../../infra/db/repo/generationCommandFactsAuthorityV2'
import {GenerationExecutionV2Repo,GenerationExecutionV2RepoError,type GenerationExecutionOperationBundleV2} from '../../infra/db/repo/generationExecutionV2Repo';import {GenerationRequestV2Repo} from '../../infra/db/repo/generationRequestV2Repo'
import {runGenerationV2AuthorityTransactionOnOwnedConnectionV2,type GenerationV2AuthorityTransactionContextV2} from '../../infra/db/repo/generationV2AuthorityTransactionInternal';import {OllamaChatNativeHistoryV2Repo} from '../../infra/db/repo/ollamaChatNativeHistoryV2Repo'
import {LocalEndpointProfileV2Repo} from '../../infra/db/repo/localEndpointProfileV2Repo';import {RuntimeCapabilityV2Repo} from '../../infra/db/repo/runtimeCapabilityV2Repo';import {projectGenerationCommandAttachmentsV2} from '../../src/next/generation-v2/domain/commandAttachmentsV2'
import {composeOllamaChatCapabilityV2} from '../../src/next/generation-v2/providers/ollama-chat/runtimeCapabilityV2';import {createOllamaChatProviderBindingV2} from '../../src/next/generation-v2/providers/ollama-chat/verifiedContractV2'
import {decodeOllamaChatEditResendCommandV2,decodeOllamaChatInitialCommandV2,decodeOllamaChatRegenerateCommandV2,decodeOllamaChatRetryCommandV2,type OllamaChatEditResendCommandV2,type OllamaChatInitialCommandV2,type OllamaChatRegenerateCommandV2,type OllamaChatRetryCommandV2} from '../../src/next/generation-v2/providers/ollama-chat/plainTextCommandsV2'
import {compileOllamaChatPreparedRequestV2} from './ollamaChatPreparedRequestCompilerV2';import {commitOllamaCurrentSnapshotV2,commitOllamaRetrySnapshotV2} from './ollamaPlainTextSnapshotCommitV2';import {issueGenerationTextCommandResultV2,type GenerationTextCommandResultV2} from './generationTextCommandResultV2'
type Current=OllamaChatInitialCommandV2|OllamaChatRegenerateCommandV2|OllamaChatEditResendCommandV2
export function createOllamaChatGenerationV2Coordinator(input:Readonly<{db:BetterSqlite3.Database;nowMs?:()=>number;createQuestionId?:()=>string;createAnswerId?:()=>string}>){
 const now=input.nowMs??Date.now,qid=input.createQuestionId??(()=>`question:${randomUUID()}`),aid=input.createAnswerId??(()=>`answer:${randomUUID()}`),graph=new ConversationGraphV2Repo(input.db),exec=new GenerationExecutionV2Repo(input.db,now),requests=new GenerationRequestV2Repo(input.db,now),history=new OllamaChatNativeHistoryV2Repo(input.db),profiles=new LocalEndpointProfileV2Repo(input.db,now),config=new GenerationConfigV2Repo(input.db,now),attachments=new AttachmentAssetV2Repo(input.db,now),caps=new RuntimeCapabilityV2Repo(input.db)
 const compile=(c:GenerationV2AuthorityTransactionContextV2,b:GenerationExecutionOperationBundleV2)=>compileOllamaChatPreparedRequestV2({context:c,execution:b,profile:profiles.get(b.snapshot.providerBinding.endpointProfileId.value),history:history.loadRequestHistory(c,b.operation.operationId.value)})
 function replay(command:{operationId:{value:string};requestFingerprint:string},action:string):GenerationTextCommandResultV2|null{const found=exec.findOperation(command.operationId.value);if(!found)return null;if(found.operation.actionKind!==action||found.operation.commandFingerprint!==command.requestFingerprint||found.snapshot.providerBinding.protocolContractId.value!=='ollama-chat-v1')throw new GenerationExecutionV2RepoError('GENERATION_V2_EXECUTION_IDEMPOTENCY_CONFLICT');return runGenerationV2AuthorityTransactionOnOwnedConnectionV2(input.db,c=>{const b=exec.findOperationInTransaction(c,command.operationId.value)!;const p=compile(c,b),projection=action==='initial_send'?graph.getInitialSendReplayProjectionInTransaction(c,command.operationId.value):graph.getGenerationReplayProjectionInTransaction(c,command.operationId.value);return issueGenerationTextCommandResultV2({kind:'idempotent_replay',execution:b,projection,preparedRequest:p,request:requests.replayPrepared(c,b,p)})})}
 function persist(c:GenerationV2AuthorityTransactionContextV2,command:Current){const raced=exec.findOperationInTransaction(c,command.operationId.value);if(raced){if(raced.operation.commandFingerprint!==command.requestFingerprint)throw new GenerationExecutionV2RepoError('GENERATION_V2_EXECUTION_IDEMPOTENCY_CONFLICT');const p=compile(c,raced),projection=command.kind==='ollama_chat_initial'?graph.getInitialSendReplayProjectionInTransaction(c,command.operationId.value):graph.getGenerationReplayProjectionInTransaction(c,command.operationId.value);return issueGenerationTextCommandResultV2({kind:'idempotent_replay',execution:raced,projection,preparedRequest:p,request:requests.replayPrepared(c,raced,p)})}
  const profile=profiles.get(command.endpointProfileId.value);if(profile.protocolContractId!=='ollama-chat-v1')throw new Error('GENERATION_V2_OLLAMA_PROFILE_CONTRACT_INVALID');const at=now(),pending=command.kind==='ollama_chat_initial'?graph.beginInitialTurn(c,{operationId:command.operationId.value,branchId:command.branchId.value,expectedHeadMessageId:command.expectedHeadMessageId?.value??null,questionId:qid(),answerRootId:aid(),userBody:command.userBody,createdAtMs:at}):command.kind==='ollama_chat_regenerate'?graph.beginAnswerAction(c,{operationId:command.operationId.value,actionKind:'regenerate_question',branchId:command.branchId.value,questionId:command.questionId.value,targetAnswerRootId:null,expectedHeadMessageId:command.expectedHeadMessageId.value,answerRootId:aid(),createdAtMs:at}):graph.beginEditedTurn(c,{operationId:command.operationId.value,mode:command.mode,branchId:command.branchId.value,sourceQuestionId:command.sourceQuestionId.value,sourceAnswerRootId:command.sourceAnswerRootId.value,expectedHeadMessageId:command.expectedHeadMessageId.value,questionId:qid(),answerRootId:aid(),userBody:command.userBody,createdAtMs:at})
  return withSynchronousGenerationCommandFactsAuthorityV2(c,config,attachments,pending.conversationId.value,projectGenerationCommandAttachmentsV2(command.commandAttachments),undefined,facts=>{const binding=createOllamaChatProviderBindingV2(profile,command.modelId.value),capability=composeOllamaChatCapabilityV2({binding,profile,resolvedAt:new Date(at).toISOString()}),saved=commitOllamaCurrentSnapshotV2({context:c,executionRepo:exec,capabilityRepo:caps,pending,command,commandFacts:facts,profile,capability});if(command.kind==='ollama_chat_initial')graph.commitInitialTurnProjection(c,pending as PendingInitialTurnV2);else if(command.kind==='ollama_chat_regenerate')graph.commitAnswerActionProjection(c,pending as PendingAnswerActionV2);else graph.commitEditedTurnProjection(c,pending as PendingEditedTurnV2);const p=compile(c,saved.bundle),projection=command.kind==='ollama_chat_initial'?graph.getInitialSendReplayProjectionInTransaction(c,command.operationId.value):graph.getGenerationReplayProjectionInTransaction(c,command.operationId.value);return issueGenerationTextCommandResultV2({kind:'created',execution:saved.bundle,projection,preparedRequest:p,request:requests.createPrepared(c,saved.bundle,p)})})}
 async function current(command:Current,action:'initial_send'|'regenerate_question'|'edit_resend'){const old=replay(command,action);if(old)return old;try{return runGenerationV2AuthorityTransactionOnOwnedConnectionV2(input.db,c=>persist(c,command))}catch(e){const winner=replay(command,action);if(winner)return winner;throw e}}
 async function retry(command:OllamaChatRetryCommandV2){const old=replay(command,command.actionKind);if(old)return old;try{return runGenerationV2AuthorityTransactionOnOwnedConnectionV2(input.db,c=>{const row=input.db.prepare('SELECT operation_id AS operationId FROM assistant_generation_snapshot_v2 WHERE answer_root_id=?').get(command.targetAnswerRootId.value) as {operationId?:unknown}|undefined;if(!row||typeof row.operationId!=='string')throw new Error('GENERATION_V2_OLLAMA_RETRY_TARGET_INVALID');const target=exec.findOperationInTransaction(c,row.operationId);if(!target||target.operation.questionId.value!==command.questionId.value||target.snapshot.providerBinding.protocolContractId.value!=='ollama-chat-v1')throw new Error('GENERATION_V2_OLLAMA_RETRY_TARGET_INVALID');const profile=profiles.get(target.snapshot.providerBinding.endpointProfileId.value),revision=target.snapshot.providerBinding.endpointBinding.kind==='provider_managed_set'?target.snapshot.providerBinding.endpointBinding.endpointSetRevision.value:'';if(profile.profileRevision!==revision)throw new Error('GENERATION_V2_OLLAMA_PROFILE_STALE');const pending=graph.beginAnswerAction(c,{operationId:command.operationId.value,actionKind:command.actionKind,branchId:command.branchId.value,questionId:command.questionId.value,targetAnswerRootId:command.targetAnswerRootId.value,expectedHeadMessageId:command.expectedHeadMessageId.value,answerRootId:aid(),createdAtMs:now()}),saved=commitOllamaRetrySnapshotV2({context:c,executionRepo:exec,pending,command,target});graph.commitAnswerActionProjection(c,pending);const p=compile(c,saved.bundle);return issueGenerationTextCommandResultV2({kind:'created',execution:saved.bundle,projection:graph.getGenerationReplayProjectionInTransaction(c,command.operationId.value),preparedRequest:p,request:requests.createPrepared(c,saved.bundle,p)})})}catch(e){const winner=replay(command,command.actionKind);if(winner)return winner;throw e}}
 return Object.freeze({submitInitial:(r:unknown)=>current(decodeOllamaChatInitialCommandV2(r),'initial_send'),retry:(r:unknown)=>retry(decodeOllamaChatRetryCommandV2(r)),regenerate:(r:unknown)=>current(decodeOllamaChatRegenerateCommandV2(r),'regenerate_question'),editResend:(r:unknown)=>current(decodeOllamaChatEditResendCommandV2(r),'edit_resend')})}
